/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AddPlaylistRouteImport } from './routes/add-playlist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaylistRoute = AddPlaylistRouteImport.update({
  id: '/add-playlist',
  path: '/add-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-playlist': typeof AddPlaylistRoute
  '/settings': typeof SettingsRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-playlist': typeof AddPlaylistRoute
  '/settings': typeof SettingsRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-playlist': typeof AddPlaylistRoute
  '/settings': typeof SettingsRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-playlist' | '/settings' | '/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-playlist' | '/settings' | '/playlist/$playlistId'
  id: '__root__' | '/' | '/add-playlist' | '/settings' | '/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlaylistRoute: typeof AddPlaylistRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-playlist': {
      id: '/add-playlist'
      path: '/add-playlist'
      fullPath: '/add-playlist'
      preLoaderRoute: typeof AddPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlaylistRoute: AddPlaylistRoute,
  SettingsRoute: SettingsRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
